import { describe, it } from "vite-plus/test";
import { RuleTester } from "vite-plus/lint/plugins-dev";
import plugin from "../src/plugin.ts";

RuleTester.describe = describe;
RuleTester.it = it;

const tester = new RuleTester({ languageOptions: { parserOptions: { lang: "ts" } } });

for (const [name, cases] of Object.entries({
  "no-object-parameters": {
    valid: [
      "function run(value: { name: string }) {}",
      "function run(value: User) {}",
      "type Input = object; function outer() { type Input = string; function run(value: Input) {} }",
      "type Loop = Loop; function run(value: Loop) {}",
      "function outer() { function run(value: Input) {} type Input = string; } type Input = object;",
    ],
    invalid: [
      { code: "function run(value: object) {}", errors: 1 },
      { code: "const run = (value: object | null) => {};", errors: 1 },
      { code: "type Box<T> = T; function run(value: Box<object>) {}", errors: 1 },
      { code: "type Callback = (value: object) => void;", errors: 1 },
      { code: "class C { constructor(public value: object) {} }", errors: 1 },
      { code: "function run(value: Input) {} type Input = object;", errors: 1 },
    ],
  },
  "no-unknown-parameters": {
    valid: [
      "function run(cause: unknown) {}",
      "function isUser(input: unknown): input is User { return true; }",
      "function check(input: unknown): asserts input is User {}",
      "function run<T>(input: T) {}",
      "type Input = unknown; function run<Input>(input: Input) {}",
      "import type { Input } from './elsewhere'; function run(input: Input) {}",
    ],
    invalid: [
      { code: "function run(input: unknown) {}", errors: 1 },
      {
        code: "type Box<T> = T; type Value = Box<unknown>; function run(input: Value) {}",
        errors: 1,
      },
      { code: "type Box<T> = T; function run(input: Box<Box<unknown>>) {}", errors: 1 },
      {
        code: "function isUser(input: unknown, other: unknown): input is User { return true; }",
        errors: 1,
      },
      { code: "interface Service { run(input: unknown): void; }", errors: 1 },
      { code: "const run = function(input: unknown) {};", errors: 1 },
      { code: "const run = (input: unknown) => {};", errors: 1 },
      { code: "declare function run(input: unknown): void;", errors: 1 },
      { code: "declare class Service { run(input: unknown): void; }", errors: 1 },
      { code: "type Callback = (input: unknown) => void;", errors: 1 },
      { code: "type Factory = new(input: unknown) => Service;", errors: 1 },
      { code: "interface Callback { (input: unknown): void; }", errors: 1 },
      { code: "interface Factory { new(input: unknown): Service; }", errors: 1 },
      { code: "declare function run(input: Input): void; type Input = unknown;", errors: 1 },
    ],
  },
  "no-unknown-returns": {
    valid: [
      "function run(): User { return user; }",
      "const run = () => value;",
      "type Promise<T> = string; function run(): Promise<unknown> { return ''; }",
      "const C = class Promise<T> { run(): Promise<unknown> { return this; } };",
      "const C = class PromiseLike<T> { run(): PromiseLike<unknown> { return this; } };",
      "import Promise = Custom.Promise; declare function load(): Promise<unknown>;",
      "import PromiseLike = Custom.PromiseLike; declare function load(): PromiseLike<unknown>;",
      "import Promise = require('./custom'); declare function load(): Promise<unknown>;",
      "export import Promise = Custom.Promise; declare function load(): Promise<unknown>;",
    ],
    invalid: [
      { code: "function run(): unknown { return value; }", errors: 1 },
      { code: "async function run(): Promise<unknown> { return value; }", errors: 1 },
      { code: "type Box<T> = T; const run = (): PromiseLike<Box<unknown>> => value;", errors: 1 },
      { code: "interface Service { run(): unknown; }", errors: 1 },
      { code: "const run = function(): unknown { return null; };", errors: 1 },
      { code: "declare function run(): unknown;", errors: 1 },
      { code: "declare class Service { run(): unknown; }", errors: 1 },
      { code: "type Callback = () => unknown;", errors: 1 },
      { code: "type Factory = new() => unknown;", errors: 1 },
      { code: "interface Callback { (): unknown; }", errors: 1 },
      { code: "interface Factory { new(): unknown; }", errors: 1 },
      { code: "function run(): Result { return null; } type Result = unknown;", errors: 1 },
      {
        code: "namespace Inner { import Promise = Custom.Promise; export declare function inside(): Promise<unknown>; } declare function outside(): Promise<unknown>;",
        errors: 1,
      },
      {
        code: "const C = class Promise<T> { run(): Promise<unknown> { return this; } }; function outside(): Promise<unknown> { return load(); }",
        errors: 1,
      },
    ],
  },
  "no-unknown-type-aliases": {
    valid: [
      "type User = { name: string };",
      "type Values = unknown[];",
      "type Loop = Loop;",
      "type Left = Right; type Right = Left;",
      "type Loop<T> = Loop<T>; type Recursive = Loop<string>;",
      "type Loop<T = T> = T; type Recursive = Loop;",
      "type Identity<T> = T;",
      "type Identity<T> = T; type Value = Identity<string>;",
    ],
    invalid: [
      { code: "type Raw = unknown;", errors: 1 },
      { code: "type Identity<T = unknown> = T; type Raw = Identity;", errors: 1 },
      { code: "type A = unknown; type B = A;", errors: 2 },
      { code: "type B = A; type A = unknown;", errors: 2 },
      { code: "type Raw = unknown | string;", errors: 1 },
      { code: "type Identity<T> = T; type Raw = Identity<unknown>;", errors: 1 },
      { code: "function run() { type Raw = unknown; }", errors: 1 },
    ],
  },
  "no-unsafe-dictionary-type": {
    valid: [
      "type Users = Record<string, User>;",
      "function run<T extends Record<string, unknown>>(value: T) {}",
      "type Record<K, V> = { value: string }; type Value = Record<string, unknown>;",
      "type User = { value: unknown };",
      "type Payload = { [K in 'value']: unknown };",
      "type Payload = { [K in 'first' | 'second']: any };",
      "type Payload = { [K in string as 'value']: unknown };",
      "type Payload = { [K in never]: unknown };",
      "type Payload = Record<'value', unknown>;",
      "type Keys = 'first' | 'second'; type Payload = Record<Keys, {}>;",
      "type Payload = Record<never, unknown>;",
      "type Dict<K extends string> = { [P in K]: unknown }; type Payload = Dict<'value'>;",
      "type Identity<T extends { nested: Record<string, unknown> }> = T;",
      "const C = class Record<K, V> { value: Record<string, unknown>; };",
      "import Record = Custom.Record; type Data = Record<string, unknown>;",
      "import Record = require('./custom'); type Data = Record<string, unknown>;",
      "type Data = Record<string, {} & { id: string }>;",
      "type Data = Record<string, {}[]>;",
      "type Data = Record<string, { value: {} } | null>;",
      "type Loop = Loop | null; type Data = Record<string, Loop>;",
    ],
    invalid: [
      { code: "type Data = Record<string, unknown>;", errors: 1 },
      { code: "type Data = Record<string, any>;", errors: 1 },
      { code: "type Data = Record<string, {} | null>;", errors: 1 },
      { code: "type Empty = {}; type Data = Record<string, Empty | null>;", errors: 1 },
      { code: "type Maybe<T> = T | null; type Data = Record<string, Maybe<{}>>;", errors: 1 },
      { code: "type Loop = Loop | {}; type Data = Record<string, Loop>;", errors: 1 },
      { code: "type Data = { [key: string]: {} | null };", errors: 1 },
      { code: "type Data = { [K in string]: {} | null };", errors: 1 },
      {
        code: "const C = (class Record<K, V> { value: Record<string, unknown>; }) as Record<string, unknown>;",
        errors: 1,
      },
      { code: "type Data = { [key: string]: object };", errors: 1 },
      { code: "interface Data { [key: string]: {}; }", errors: 1 },
      { code: "type Wide = unknown; type Data = Record<string, Wide>;", errors: 1 },
      { code: "type Data = { [K in string]: unknown };", errors: 1 },
      { code: "type Data = { [K in 'value' as string]: unknown };", errors: 1 },
      { code: "type Data = { [K in string as K]: unknown };", errors: 1 },
      {
        code: "type Dict<K extends string> = { [P in K]: unknown }; type Data = Dict<string>;",
        errors: 1,
      },
      { code: "type Key = string; type Data = Record<Key, unknown>;", errors: 1 },
      { code: "type Data = Record<number | symbol, unknown>;", errors: 1 },
      {
        code: "type Identity<T extends Record<string, unknown> = Record<string, unknown>> = T;",
        errors: 1,
      },
    ],
  },
  "no-trivial-type-aliases": {
    valid: [
      "type Raw = unknown;",
      "type Id = string & { readonly brand: unique symbol };",
      "type State = 'a' | 'b';",
      "type User = { name: string };",
      "type Identity<T> = T;",
      "function run() { type Local = string; }",
      "import type { User } from './user'; type Account = User;",
    ],
    invalid: [
      { code: "type Id = string;", errors: 1 },
      { code: "type A = number; type B = A;", errors: 2 },
      { code: "type B = A; type A = number;", errors: 2 },
      { code: "export type Flag = boolean;", errors: 1 },
    ],
  },
  "no-known-value-widening": {
    valid: [
      "function run(input: unknown) { const value: unknown = input; }",
      "const handlers = { start } satisfies Record<string, Handler>;",
      "const empty: Record<string, Handler> = {};",
      "const handlers: Record<'start', Handler> = { start };",
      "const user: User = { name: 'Kim' };",
      "type User = { name: string }; const user: User = { name: 'Kim' };",
      "type User = { name: string }; type Alias = User; const user: Alias = { name: 'Kim' };",
      "type Broad = {}; function run<Broad>(value: Broad) { const result: Broad = value; }",
      "type Loop = Loop; declare const value: Loop;",
      "function accept(...values: number[]) {} accept(1, 2);",
      "function accept(...values: unknown[]) {} declare const value: unknown; accept(value);",
      "function accept(...values: unknown[]) {} declare const values: number[]; accept(...values, 1);",
      "function accept<T>(...values: T[]) {} accept(1, 2);",
      "function accept(...values: any[]) {} accept(1, 2);",
      "function accept(...values: [number, string?]) {} accept(1, 'x');",
      "function accept(...values: [...unknown[], number]) {} accept(1, 2);",
      "type Loop = [...Loop]; function accept(...values: Loop) {} accept(1, 2);",
      "type Array<T> = Custom; function accept(...values: Array<unknown>) {} accept(1, 2);",
      "declare function accept(...values: unknown[]): void; declare function accept(...values: number[]): void; accept(1, 2);",
      "function accept(value: number) {} accept(1, 2);",
      "const handlers: { [K in 'start']: Handler } = { start };",
      "const handlers: { [K in string as 'start']: Handler } = { start };",
      "type Keys = 'start' | 'stop'; const handlers: { [K in Keys]: Handler } = { start, stop };",
      "const empty: { [K in string]: Handler } = {};",
      "function run<K extends string>() { const handlers: { [P in K]: Handler } = { start }; }",
      "declare function id<T>(x: T): T; declare const input: unknown; const value: unknown = id(input);",
      "declare function id<T>(x: T): T | null; declare const input: unknown; const value: unknown = id(input);",
      "type Result<T> = T; declare function id<T>(x: T): Result<T>; declare const input: unknown; const value: unknown = id(input);",
      "function run<T>(input: T | null) { const value: unknown = input; }",
      "type Loop = Loop | null; declare function load(): Loop; const value: unknown = load();",
      "declare const input: any; const value: unknown = input + 1;",
      "declare const input: unknown; const value: unknown = input && true;",
      "declare const input: unknown; const value: unknown = input || true;",
      "declare const input: unknown; const value: unknown = input ?? true;",
      "declare function choose(value: string): string; declare function choose(value: unknown): unknown; declare const input: unknown; const output: unknown = choose(input);",
      "function choose(value: string): string; function choose(value: unknown): unknown; function choose(value: unknown): unknown { return value; } declare const input: unknown; const pick = choose; const output: unknown = pick(input);",
      "declare function choose(value: unknown, mode: 'raw'): unknown; declare function choose(value: string, mode: 'text'): string; choose('x', 'text');",
      "const value = new Date();",
      "declare const pair: [string, unknown]; function accept(first: string, second: unknown, value: number) {} accept(...pair, 1);",
      "declare const pair: [string, unknown]; function accept(this: void, first: string, second: unknown, value: number) {} accept(...pair, 1);",
      "declare const pair: [string, string]; function accept(first: string, second: string, value: unknown) {} accept(...pair, 1);",
      "declare const empty: []; function accept(value: unknown) {} accept(...empty, 1);",
      "declare const pair: [string]; function accept(first: string, value: unknown) {} accept(...pair, 1);",
      "function accept<T>(value: T) {} accept<string>('x');",
      "function accept<T = unknown>(value: T) {} accept(1);",
      "declare function id<T, U = U>(value: U): U; const output: unknown = id<number>(1);",
      "function accept<T, U = unknown>(first: T, second: U) {} accept(1, 2);",
      "function accept<T>(value: T) {} accept<any>(1);",
      "function accept<T>(value: T) {} accept<Record<string, Handler>>({});",
      "function accept<T>(value: T) {} accept<Record<'start', Handler>>({ start });",
      "function outer<T>(input: T) { function accept<U>(value: U) {} accept<T>(input); }",
      "declare function id<T = unknown>(value: T): T; declare const input: unknown; const output: unknown = id(input);",
      "function accept<T>(value: T) {} declare const input: unknown; accept<unknown>(input);",
      "interface T { id: number; } type Contract = T; function accept<T>(value: Contract) {} accept<unknown>({ id: 1 });",
      "declare function choose<T>(value: T): string; declare function choose<T>(value: unknown): unknown; declare const input: unknown; const value: unknown = choose<unknown>(input);",
      "const value = new Date() satisfies object;",
      "import Record = Custom.Record; const value: Record<string, Handler> = { start };",
      "declare const input: unknown; const value: unknown = enabled ? { id: 1 } : input;",
      "declare const input: unknown; const value: unknown = enabled ? input : { id: 1 };",
      "function accept(this: unknown, value: string) {} accept('x');",
      "function accept(this: void, value: string) {} accept('x');",
      "function accept(this: void, value: unknown) {} declare const input: unknown; accept(input);",
      "declare function accept(this: void, value: string): string; declare function accept(this: void, value: unknown): unknown; accept('x');",
      "declare const raw: unknown; const value: unknown = (raw as unknown) satisfies unknown;",
    ],
    invalid: [
      { code: "const value: unknown = 'ready';", errors: 1 },
      { code: "type Broad = {}; const value: Broad = 1;", errors: 1 },
      { code: "type Broad = {}; type Alias = Broad; const value: Alias = 1;", errors: 1 },
      { code: "function accept<T>(value: T) {} accept<{}>(1);", errors: 1 },
      { code: "type Broad = {} | null; const value: Broad = 1;", errors: 1 },
      { code: "const value: {} | null = 1;", errors: 1 },
      { code: "type Broad = {}; function run(): Broad { return 1; }", errors: 1 },
      { code: "type Broad = {}; let value: Broad; value = 1;", errors: 1 },
      { code: "function accept(...values: unknown[]) {} accept(1, 2);", errors: 2 },
      { code: "function accept(...values: Array<unknown>) {} accept(1, 2);", errors: 2 },
      {
        code: "function accept(this: void, label: string, ...values: unknown[]) {} accept('x', 1, 2);",
        errors: 2,
      },
      {
        code: "type Values<T> = T[]; function accept<T>(...values: Values<T>) {} accept<unknown>(1, 2);",
        errors: 2,
      },
      {
        code: "function accept(...values: [string, unknown, number]) {} accept('x', 1, 2);",
        errors: 1,
      },
      {
        code: "function accept(...values: [first: string, second: unknown]) {} accept('x', 1);",
        errors: 1,
      },
      { code: "function accept(...values: [string, unknown?]) {} accept('x', 1);", errors: 1 },
      {
        code: "function accept(...values: [first: string, second?: unknown]) {} accept('x', 1);",
        errors: 1,
      },
      {
        code: "function accept(...values: [string, ...unknown[]]) {} accept('x', 1, 2);",
        errors: 2,
      },
      {
        code: "function accept(...values: [first: string, ...rest: unknown[]]) {} accept('x', 1, 2);",
        errors: 2,
      },
      {
        code: "type Tail<T> = T[]; type Values<T> = [string, ...Tail<T>]; function accept<T>(...values: Values<T>) {} accept<unknown>('x', 1, 2);",
        errors: 2,
      },
      { code: "function accept(...values: readonly unknown[]) {} accept(1, 2);", errors: 2 },
      {
        code: "function accept(...values: Readonly<[string, unknown]>) {} accept('x', 1);",
        errors: 1,
      },
      {
        code: "const accept = (...values: unknown[]) => {}; const alias = accept; alias(1, 2);",
        errors: 2,
      },
      {
        code: "function accept(...values: unknown[]) {} declare const values: number[]; accept(1, ...values, 2);",
        errors: 1,
      },
      {
        code: "function accept(first: unknown, ...values: unknown[]) {} accept(1, 2, 3);",
        errors: 3,
      },
      {
        code: "function accept(...values: [unknown, ...unknown[], number]) {} accept(1, 2, 3);",
        errors: 1,
      },
      { code: "const value: unknown = enabled ? { id: 1 } : { id: 2 };", errors: 1 },
      { code: "const shared = 1; const value: unknown = enabled ? shared : shared;", errors: 1 },
      { code: "const value: unknown = enabled ? (other ? 1 : 2) : null;", errors: 1 },
      {
        code: "declare const enabled: unknown; const value: unknown = enabled ? 1 : 'x';",
        errors: 1,
      },
      { code: "function accept(this: void, value: unknown) {} accept(1);", errors: 1 },
      {
        code: "function accept(this: void, first: string, value: unknown) {} accept('x', 1);",
        errors: 1,
      },
      {
        code: "declare function accept(this: void, value: unknown): void; const alias = accept; alias(1);",
        errors: 1,
      },
      { code: "const accept = function(this: void, value: unknown) {}; accept(1);", errors: 1 },
      { code: "let value: unknown; value = 123;", errors: 1 },
      { code: "const value: unknown = 123 as unknown;", errors: 1 },
      { code: "const value: unknown = (123 as unknown) satisfies unknown;", errors: 1 },
      { code: "const value: unknown = (123 as unknown)!;", errors: 1 },
      { code: "const value: unknown = new Date();", errors: 1 },
      { code: "class User { name = 'Kim'; } const value: object = new User();", errors: 1 },
      { code: "const date = new Date(); const value: unknown = date;", errors: 1 },
      { code: "function make(): unknown { return new Date(); }", errors: 1 },
      {
        code: "declare function choose(value: string): string; const output: unknown = choose('x');",
        errors: 1,
      },
      { code: "const handlers: Record<string, Handler> = { start };", errors: 1 },
      { code: "const value: { name: string } = { name: 'Kim' };", errors: 1 },
      {
        code: "function isUser(value: unknown): value is User { return true; } const user: User = load(); isUser(user);",
        errors: 1,
      },
      { code: "function run(): unknown { return 123; }", errors: 1 },
      { code: "const run = (): object => ({ name: 'Kim' });", errors: 1 },
      { code: "accept(1); function accept(value: unknown) {}", errors: 1 },
      {
        code: "declare const values: string[]; function accept(value: unknown, ...rest: string[]) {} accept(1, ...values);",
        errors: 1,
      },
      { code: "function accept<T>(value: T) {} accept<unknown>(1);", errors: 1 },
      {
        code: "type Contract<T> = T; function accept<T>(value: Contract<T>) {} accept<unknown>(1);",
        errors: 1,
      },
      {
        code: "function accept<T, U = unknown>(first: T, second: U) {} accept<number>(1, 2);",
        errors: 1,
      },
      { code: "function accept<T, U = T>(value: U) {} accept<unknown>(1);", errors: 1 },
      {
        code: "function accept<T>(this: void, value: T) {} const alias = accept; alias<unknown>(1);",
        errors: 1,
      },
      { code: "function accept<T>(value: T) {} accept<object>({ id: 1 });", errors: 1 },
      {
        code: "function accept<T>(value: T) {} accept<Record<string, Handler>>({ start });",
        errors: 1,
      },
      {
        code: "function id<T>(value: T): T { return value; } const output: unknown = id<number>(1);",
        errors: 1,
      },
      {
        code: "type Result<T> = T; declare function load<T>(): Result<T> | null; const output: unknown = load<number>();",
        errors: 1,
      },
      {
        code: "declare function load<T, U = T>(): U; const output: unknown = load<number>();",
        errors: 1,
      },
      {
        code: "function id<T>(value: T): T { return value; } const output: unknown = id<unknown>(1);",
        errors: 1,
      },
      { code: "const handlers: { [K in string]: Handler } = { start };", errors: 1 },
      { code: "const handlers: { [K in number]: Handler } = { 0: start };", errors: 1 },
      { code: "const handlers: { [K in symbol]: Handler } = { [key]: start };", errors: 1 },
      { code: "const handlers: { [K in any]: Handler } = { start };", errors: 1 },
      { code: "const handlers: { [K in 'start' as string]: Handler } = { start };", errors: 1 },
      { code: "const handlers: { [K in string as K]: Handler } = { start };", errors: 1 },
      {
        code: "type Key = string; const handlers: { [K in Key]: Handler } = { start };",
        errors: 1,
      },
      {
        code: "type Dict<K extends string> = { [P in K]: Handler }; const handlers: Dict<string> = { start };",
        errors: 1,
      },
      {
        code: "type Rename<K> = K; const handlers: { [K in string as Rename<K>]: Handler } = { start };",
        errors: 1,
      },
      ...["===", "!==", "==", "!=", "<", "<=", ">", ">="].map((operator) => ({
        code: `declare const input: any; const value: unknown = input ${operator} 1;`,
        errors: 1,
      })),
      { code: "function run(input: object) { const value: unknown = 'x' in input; }", errors: 1 },
      {
        code: "function run(input: unknown) { const value: unknown = input instanceof Date; }",
        errors: 1,
      },
      {
        code: "declare function wrap<T>(x: T): T[]; declare const input: unknown; const value: unknown = wrap(input);",
        errors: 1,
      },
      {
        code: "declare function wrap<T>(x: T): { value: T }; declare const input: unknown; const value: unknown = wrap(input);",
        errors: 1,
      },
      {
        code: "declare function wrap<T>(x: T): Promise<T>; declare const input: unknown; const value: unknown = wrap(input);",
        errors: 1,
      },
      {
        code: "function outer<T>() { function inner() { interface T { id: string; } function get(): T { return { id: 'x' }; } const value: unknown = get(); } }",
        errors: 1,
      },
      {
        code: "function outer<T>() { function inner() { interface T { id: string; } const item: T = load(); const value: unknown = item; } }",
        errors: 1,
      },
    ],
  },
  "no-widen-then-assert": {
    valid: [
      "function run(input: unknown) { return input as User; }",
      "const value: User = load(); const alias = value; alias as User;",
      "let erased: unknown = 1; erased = input; erased as User;",
      "const value: unknown = [1]; value as const;",
      "declare function id<T>(x: T): T; declare const input: unknown; const value: unknown = id(input); value as User;",
      "declare function id<T>(x: T): T | null; declare const input: unknown; const value: unknown = id(input); value as User;",
      "declare function choose(value: string): string; declare function choose(value: unknown): unknown; declare const input: unknown; const output: unknown = choose(input); output as User;",
      "declare const raw: unknown; const erased = (raw as unknown)!; erased as number;",
      "const value = 123 satisfies number; value as number;",
      "type User = { name: string }; const user: User = { name: 'Kim' }; user as User;",
      "declare const input: unknown; const value: unknown = enabled ? { id: 1 } : input; value as User;",
      "const value = (123 as const)!; value as number;",
      "function id<T>(value: T): T { return value; } const output: unknown = id<unknown>(1); output as User;",
    ],
    invalid: [
      {
        code: "const user: User = load(); const erased: unknown = user; const result = erased as Admin;",
        errors: 1,
      },
      { code: "const erased: unknown = 123; const alias = erased; alias as number;", errors: 1 },
      { code: "const erased: any = { name: 'Kim' }; erased as User;", errors: 1 },
      { code: "erased as number; const erased: unknown = 123;", errors: 1 },
      { code: "const value: unknown = new Date(); value as Date;", errors: 1 },
      { code: "type Broad = {}; const value: Broad = 1; value as number;", errors: 1 },
      { code: "type Broad = {}; const value = 1 as Broad; value as number;", errors: 1 },
      { code: "type Broad = {} | null; const value: Broad = 1; value as number;", errors: 1 },
      {
        code: "function id<T>(value: T): T { return value; } const output: unknown = id<number>(1); output as User;",
        errors: 1,
      },
      { code: "const value: unknown = enabled ? { id: 1 } : { id: 2 }; value as User;", errors: 1 },
      { code: "const erased = (123 as unknown)!; erased as number;", errors: 1 },
      { code: "const erased = (123 as unknown) satisfies unknown; erased as number;", errors: 1 },
      {
        code: "const erased = ((123 as unknown) satisfies unknown)!; const alias = erased; alias as number;",
        errors: 1,
      },
      { code: "const erased = (<unknown>123)!; erased as number;", errors: 1 },
      { code: "const erased = (123 as unknown); erased as number;", errors: 1 },
      {
        code: "const value = { name: 'Kim' } as unknown; const result = value as User;",
        errors: 1,
      },
    ],
  },
} satisfies Record<string, RuleTester.TestCases>)) {
  tester.run(name, plugin.rules[name]!, cases);
}
