import type { RuleTester } from "vite-plus/lint/plugins-dev";
import plugin from "../../src/plugin.ts";
import { tester } from "../helpers/rule-tester.ts";

const cases = {
  valid: [
    "function run(input: unknown) { const value: unknown = input; }",
    "function run(undefined: unknown) { const value: unknown = undefined; }",
    "function run(input: unknown) { const undefined = input; const value: unknown = undefined; }",
    "import { undefined } from 'source'; const value: unknown = undefined;",
    "function run(value: unknown = load()) {}",
    "function run(value = 1) {}",
    "class State { value: unknown = load(); accessor other: unknown = load(); }",
    "class State { value: number = 1; accessor other = 1; }",
    "class State { value: unknown; accessor other: unknown; }",
    "class State { constructor(public value: unknown = load()) {} }",
    "class State { value: Record<string, Handler> = {}; accessor other: Record<string, Handler> = {}; }",
    "function run(value: Record<string, Handler> = {}) {}",
    "const handlers = { start } satisfies Record<string, Handler>;",
    "const empty: Record<string, Handler> = {};",
    "const empty = {}; const alias = empty; const handlers: Record<string, Handler> = alias;",
    "const handlers: Record<'start', Handler> = { start };",
    "type User = { name: string }; const user: User = { name: 'Kim' };",
    "const value: { name: string } = { name: 'Kim' };",
    "function createUser(): { name: string } { return { name: 'Kim' }; }",
    "function greet(user: { name: string } = { name: 'Guest' }) {}",
    "class State { user: { name: string } = { name: 'Kim' }; accessor other: { name: string } = { name: 'Lee' }; }",
    "const value = { name: 'Kim' } as { name: string };",
    "function accept(value: unknown) {} accept(1);",
    "declare const load: () => number; const value: unknown = load();",
    "const value: unknown = enabled ? 1 : 2;",
    "type Hidden<T> = T; const value: Hidden<unknown> = 1;",
    "type Result<T> = T extends string ? string : unknown; declare const input: Result<number>; const value: unknown = input;",
  ],
  invalid: [
    { code: "const value: unknown = 'ready';", errors: 1 },
    { code: "const value: unknown = undefined;", errors: 1 },
    { code: "const value: unknown = null;", errors: 1 },
    { code: "const empty = undefined; const value: unknown = empty;", errors: 1 },
    { code: "function run(value: unknown = undefined) {}", errors: 1 },
    { code: "class State { value: unknown = undefined; }", errors: 1 },
    { code: "function run(value: unknown = 1) {}", errors: 1 },
    { code: "class State { value: unknown = 1; }", errors: 1 },
    { code: "class State { accessor value: unknown = 1; }", errors: 1 },
    { code: "class State { constructor(public value: unknown = 1) {} }", errors: 1 },
    { code: "const known = 1; const value: unknown = known;", errors: 1 },
    { code: "declare const known: number; const value: unknown = known;", errors: 1 },
    { code: "type Broad = {}; const value: Broad = 1;", errors: 1 },
    { code: "let value: unknown; value = 1;", errors: 1 },
    { code: "function run(): unknown { return 1; }", errors: 1 },
    { code: "const run = (): object => ({ name: 'Kim' });", errors: 1 },
    { code: "const handlers: Record<string, Handler> = { start };", errors: 1 },
    {
      code: "const known = { start }; const handlers: Record<string, Handler> = known;",
      errors: 1,
    },
    { code: "const value: {} = 1;", errors: 1 },
    { code: "const value: { [key: string]: string } = { name: 'Kim' };", errors: 1 },
    { code: "const value: unknown = new Date();", errors: 1 },
    { code: "const value: unknown = (1 as unknown)!;", errors: 1 },
  ],
} satisfies RuleTester.TestCases;

tester.run("no-known-value-widening", plugin.rules["no-known-value-widening"]!, cases);
