import type { OxlintConfig } from "vite-plus/lint";

export const nativeLint: OxlintConfig = {
  plugins: ["typescript", "oxc", "unicorn"],
  categories: {
    correctness: "off",
    nursery: "off",
    pedantic: "off",
    perf: "off",
    restriction: "off",
    style: "off",
    suspicious: "off",
  },
  options: { typeAware: true, typeCheck: true },
  rules: {
    "typescript/no-floating-promises": [
      "error",
      { ignoreVoid: true, checkThenables: false, ignoreIIFE: false },
    ],
    "typescript/await-thenable": "error",
    "no-async-promise-executor": "error",
    "no-unsafe-optional-chaining": ["error", { disallowArithmeticOperators: true }],
    "valid-typeof": ["error", { requireStringLiterals: false }],
    "typescript/no-array-delete": "error",
    "typescript/no-base-to-string": [
      "error",
      { checkUnknown: false, ignoredTypeNames: ["Error", "RegExp", "URL", "URLSearchParams"] },
    ],
    "typescript/no-duplicate-type-constituents": [
      "error",
      { ignoreUnions: false, ignoreIntersections: false },
    ],
    "typescript/no-for-in-array": "error",
    "typescript/no-implied-eval": "error",
    "typescript/no-meaningless-void-operator": ["error", { checkNever: false }],
    "typescript/no-misused-spread": ["error", { allow: [] }],
    "typescript/no-redundant-type-constituents": "error",
    "typescript/no-unsafe-unary-minus": "off",
    "typescript/no-useless-default-assignment": "warn",
    "typescript/require-array-sort-compare": ["error", { ignoreStringArrays: true }],
    "typescript/restrict-template-expressions": [
      "error",
      {
        allowAny: true,
        allowArray: false,
        allowBoolean: true,
        allowNullish: true,
        allowNumber: true,
        allowRegExp: true,
        allowNever: false,
        allow: [{ from: "lib", name: ["Error", "URL", "URLSearchParams"] }],
      },
    ],
    "typescript/unbound-method": ["error", { ignoreStatic: false }],
    "constructor-super": "off",
    "for-direction": "error",
    "getter-return": "off",
    "no-caller": "off",
    "no-class-assign": "off",
    "no-compare-neg-zero": "error",
    "no-cond-assign": ["error", "always"],
    "no-const-assign": "off",
    "no-constant-binary-expression": ["error", { checkRelationalComparisons: true }],
    "no-constant-condition": ["error", { checkLoops: "allExceptWhileTrue" }],
    "no-control-regex": "warn",
    "no-debugger": "error",
    "no-delete-var": "off",
    "no-dupe-class-members": "off",
    "no-dupe-else-if": "error",
    "no-dupe-keys": "off",
    "no-duplicate-case": "error",
    "no-empty-character-class": "error",
    "no-empty-pattern": ["error", { allowObjectPatternsAsParameters: false }],
    "no-empty-static-block": "error",
    "no-eval": ["error", { allowIndirect: false }],
    "no-ex-assign": "error",
    "no-extra-boolean-cast": ["error", { enforceForInnerExpressions: false }],
    "no-func-assign": "off",
    "no-global-assign": ["error", { exceptions: [] }],
    "no-import-assign": "error",
    "no-invalid-regexp": ["error", { allowConstructorFlags: [] }],
    "no-irregular-whitespace": [
      "error",
      {
        skipStrings: true,
        skipComments: false,
        skipRegExps: true,
        skipTemplates: true,
        skipJSXText: true,
      },
    ],
    "no-iterator": "off",
    "no-loss-of-precision": "error",
    "no-misleading-character-class": ["error", { allowEscape: false }],
    "no-new-native-nonconstructor": "off",
    "no-nonoctal-decimal-escape": "off",
    "no-obj-calls": "off",
    "no-self-assign": ["error", { props: true }],
    "no-setter-return": "off",
    "no-shadow-restricted-names": ["error", { reportGlobalThis: true }],
    "no-sparse-arrays": "error",
    "no-this-before-super": "off",
    "no-unassigned-vars": "error",
    "no-unreachable": "error",
    "no-unsafe-finally": "error",
    "no-unsafe-negation": "off",
    "no-unused-expressions": [
      "error",
      {
        allowShortCircuit: false,
        allowTernary: false,
        allowTaggedTemplates: false,
        enforceForJSX: false,
        ignoreDirectives: false,
      },
    ],
    "no-unused-labels": "error",
    "no-unused-private-class-members": "error",
    "no-unused-vars": [
      "error",
      {
        vars: "all",
        args: "all",
        caughtErrors: "all",
        argsIgnorePattern: "^_",
        caughtErrorsIgnorePattern: "^_",
        ignoreRestSiblings: true,
      },
    ],
    "no-useless-backreference": "error",
    "no-useless-catch": "error",
    "no-useless-escape": ["error", { allowRegexCharacters: [] }],
    "no-useless-rename": [
      "error",
      { ignoreDestructuring: false, ignoreImport: false, ignoreExport: false },
    ],
    "no-with": "off",
    "require-yield": "error",
    "use-isnan": "off",
    "oxc/bad-array-method-on-arguments": "off",
    "oxc/bad-char-at-comparison": "error",
    "oxc/bad-comparison-sequence": "error",
    "oxc/bad-match-all-arg": "error",
    "oxc/bad-min-max-func": "error",
    "oxc/bad-object-literal-comparison": "off",
    "oxc/bad-replace-all-arg": "error",
    "oxc/const-comparisons": "error",
    "oxc/double-comparisons": "warn",
    "oxc/erasing-op": "warn",
    "oxc/missing-throw": "error",
    "oxc/number-arg-out-of-range": "off",
    "oxc/only-used-in-recursion": "warn",
    "oxc/uninvoked-array-callback": "off",
    "typescript/no-duplicate-enum-values": "error",
    "typescript/no-extra-non-null-assertion": "error",
    "typescript/no-misused-new": "error",
    "typescript/no-non-null-asserted-optional-chain": "error",
    "typescript/no-this-alias": ["error", { allowDestructuring: true, allowedNames: [] }],
    "typescript/no-unnecessary-parameter-property-assignment": "warn",
    "typescript/no-unsafe-declaration-merging": "error",
    "typescript/no-useless-empty-export": "off",
    "typescript/no-wrapper-object-types": "error",
    "typescript/prefer-as-const": "error",
    "typescript/prefer-namespace-keyword": "off",
    "typescript/triple-slash-reference": [
      "error",
      { lib: "always", path: "never", types: "prefer-import" },
    ],
    "unicorn/no-await-in-promise-methods": "error",
    "unicorn/no-empty-file": "warn",
    "unicorn/no-invalid-fetch-options": "error",
    "unicorn/no-invalid-remove-event-listener": "error",
    "unicorn/no-new-array": "error",
    "unicorn/no-single-promise-in-promise-methods": "off",
    "unicorn/no-thenable": "warn",
    "unicorn/no-unnecessary-await": "off",
    "unicorn/no-useless-fallback-in-spread": "error",
    "unicorn/no-useless-length-check": "warn",
    "unicorn/no-useless-spread": "warn",
    "unicorn/prefer-set-size": "error",
    "unicorn/prefer-string-starts-ends-with": "off",
    "oxc/no-accumulating-spread": "error",
    "typescript/no-misused-promises": [
      "error",
      { checksConditionals: true, checksSpreads: true, checksVoidReturn: true },
    ],
    "typescript/switch-exhaustiveness-check": [
      "error",
      {
        allowDefaultCaseForExhaustiveSwitch: true,
        considerDefaultExhaustiveForUnions: false,
        requireDefaultForNonUnion: false,
      },
    ],
    "typescript/no-unsafe-assignment": "error",
    "typescript/no-unsafe-argument": "error",
    "typescript/no-unsafe-call": "error",
    "typescript/no-unsafe-member-access": ["error", { allowOptionalChaining: false }],
    "typescript/no-unsafe-return": "error",
    "typescript/only-throw-error": [
      "error",
      { allow: [], allowRethrowing: true, allowThrowingAny: true, allowThrowingUnknown: true },
    ],
    "typescript/no-explicit-any": ["warn", { fixToUnknown: false, ignoreRestArgs: false }],
  },
};
